global:
  evaluation_interval: 5m
  scrape_interval: 5m
  scrape_timeout: 5m
scrape_configs:
- job_name: 'collector'
  static_configs:
  - targets: [ 'metrics-prometheus-collector:8080', 'metrics-prometheus-collector:8585' ]
