apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  template:
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - { name: grafana, containerPort: 3000 }
        resources:
          requests: { cpu: "500m", memory: 500M }
          limits:   { cpu: "1",    memory: 1Gi  }
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap: { name: grafana-datasources, defaultMode: 420 }

