apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app: grafana
  includeTemplates: true
  includeSelectors: true

resources:
- grafana.deployment.yaml
- grafana.service.yaml

configMapGenerator:
- name: grafana-datasources
  files: [ configmaps/grafana.yml ]
