apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app: prometheus
  includeTemplates: true
  includeSelectors: true

resources:
- prometheus.deployment.yaml
- prometheus.service.yaml
- prometheus.serviceaccount.yaml

configMapGenerator:
- name: prometheus-config
  files: [ configmaps/prometheus.yml ]
