apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app: metrics-node-sampler
  includeSelectors: true
  includeTemplates: true

resources:
- sampler.daemonset.yaml
- sampler.service.yaml
- sampler.serviceaccount.yaml

configMapGenerator:
- name: metrics-node-sampler
  files: [ configmaps/sampler.yaml ]
  options:
    disableNameSuffixHash: true
