apiVersion: v1
kind: Service
metadata:
  name: metrics-prometheus-collector
spec:
  type: ClusterIP
  ports:
  - { name: metrics, port: 8080, protocol: TCP, targetPort: metrics }
  - { name: healthz, port: 8090, protocol: TCP, targetPort: healthz }
  - { name: proto,   port: 9090, protocol: TCP, targetPort: proto }
