apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-prometheus-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-prometheus-collector
subjects:
- kind: ServiceAccount
  name: metrics-prometheus-collector
