apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-prometheus-collector
rules:
- apiGroups:  [ "", "apps", "batch", "quotamanagement.usagemetricscollector.sigs.k8s.io"]
  resources: [ "*" ]
  verbs: [ get, list, watch ]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: [ get, create, patch, update, delete ]
- apiGroups: [""]
  resources: ["events"]
  verbs: [ create, watch ]
