apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app: metrics-prometheus-collector
  includeTemplates: true
  includeSelectors: true

resources:
- collector.deployment.yaml
- collector.role.yaml
- collector.rolebinding.yaml
- collector.service.yaml
- collector.serviceaccount.yaml

configMapGenerator:
- name: metrics-prometheus-collector
  files: [ configmaps/collector.yaml ]
  options:
    disableNameSuffixHash: true
