name: Release

on:
  push:
    # Trigger this workflow only when a tag is pushed
    tags:
      - 'v*.*.*'  # Adjust pattern if needed

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Verify formatting
        run: |
          cd cmd/container-monitor
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files need formatting:"
            echo "$UNFORMATTED"
            exit 1
          fi

      - name: Tidy
        run: go mod tidy

      - name: Build x64
        working-directory: cmd/container-monitor
        run: GOOS=linux GOARCH=amd64 go build -o container-monitor-linux-amd64 .

      - name: Build arm64
        working-directory: cmd/container-monitor
        run: GOOS=linux GOARCH=arm64 go build -o container-monitor-linux-arm64 .

      - name: Release container-monitor ${{ github.ref_name }}
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            cmd/container-monitor/container-monitor-linux-amd64
            cmd/container-monitor/container-monitor-linux-arm64
          token: ${{ secrets.GITHUB_TOKEN }}
