name: Release

on:
  push:
    # Trigger this workflow only when a tag is pushed
    tags:
      - 'v*.*.*'  # Adjust pattern if needed

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Verify formatting
        run: |
          cd cmd/container-monitor
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files need formatting:"
            echo "$UNFORMATTED"
            exit 1
          fi

      - name: Build
        run: |
          cd cmd/container-monitor
          go mod tidy
          go build .

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release container-monitor ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cmd/container-monitor/container-monitor
          asset_name: "container-monitor"
          asset_content_type: application/octet-stream
