name: Release

on:
  push:
    # Trigger this workflow only when a tag is pushed
    tags:
      - 'v*.*.*'  # Adjust pattern if needed

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Verify formatting
        run: |
          cd cmd/container-monitor
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files need formatting:"
            echo "$UNFORMATTED"
            exit 1
          fi

      - name: Build
        run: |
          cd cmd/container-monitor
          go mod tidy
          go build .

      - name: Release container-monitor ${{ github.ref_name }}
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: cmd/container-monitor/container-monitor
          token: ${{ secrets.GITHUB_TOKEN }}